# Generated by Django 4.2.8 on 2023-12-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_weeklysalary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysalary',
            old_name='total_salary',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='weeklysalary',
            old_name='total_salary',
            new_name='salary',
        ),
    ]
