# Generated by Django 4.2.8 on 2023-12-13 21:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courier', '0003_rename_total_salary_dailysalary_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsuccessfulUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField()),
                ('courier_name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
                ('income', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
